// CodeVue/src/components/landpage/Equipe.vue
<template>
    <div class="container-fluid">
  <div class="row conteudo">
    <div class="col centro"> <!-- Alterar acionador para scrollspy -->
      <h2>Equipe</h2>
    </div>
  </div>
  <div class="row fix-height">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
    </div>
  </div>
</div>
</template>

<script>
export default {
}
</script>

<style scoped>
.redondo{
    height: 200px;
    width: 200px;
    border-radius: 50%;
}
img{
    left: 25%;
}
.fix-height{
    min-height: fill;
}
.centro{
    text-align: center;
}
.conteudo{
    padding-top: 30px;
}
h4{
    padding-top: 30px;
}
</style>

// CodeOnDemand/src/app/components/equipe/equipe.component.ts
import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery'

@Component({
  selector: 'app-equipe',
  templateUrl: './equipe.component.html',
  styleUrls: ['./equipe.component.scss']
})
export class EquipeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  showElements(){
    $("#membro1").removeClass("hidden-sm-up").addClass("animated bounceInRight");
    $("#membro2").removeClass("hidden-sm-up").addClass("animated bounceInUp");
    $("#membro3").removeClass("hidden-sm-up").addClass("animated bounceInLeft");
    $("#membro4").removeClass("hidden-sm-up").addClass("animated bounceInRight");
    $("#membro5").removeClass("hidden-sm-up").addClass("animated bounceInUp");
    $("#membro6").removeClass("hidden-sm-up").addClass("animated bounceInLeft");
  }
}

<div class="container-fluid">
  <div class="row conteudo">
    <div class="col centro" (click)="showElements" (show)="showElements()"> <!-- Alterar acionador para scrollspy -->
      <h2>Equipe</h2>
    </div>
  </div>
  <div class="row fix-height">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro1" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro2" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro3" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro4" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro5" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 centro conteudo">
      <div id="membro6" class="hidden-sm-up">
        <img class="redondo" src="http://placehold.it/200x200">
        <h4>Nome do cidadão</h4>
        <p>Descrição do cidadão</p>
      </div>
    </div>
  </div>
</div>
